### ISSUE TITLE
Error in fitting a model with categorical variable

### ISSUE THREAD

**Issue by cathytao** [rosemm/rexamples#2]
> generated_data$prob <- predict (model, newdata=generated_data, type = 'response')
Error in factor(stateno) : object 'stateno' not found

As shown above, when I try to fit the predicted value using R, since my model has categorical variable 'stateno', it prohibits me from proceeding and obtaining the predicted value. Any one can help on this line?

Thanks!

**Comment by rosemm** [comment]
What code are you trying to run (which function or file)?
